name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feat/gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: "5.4"

    - name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        luarocks install --local luxtra-0.1.0-1.rockspec

    - name: Generate site
      run: |
        lua main.lua build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: 'docs/'

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: gh-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
